logging:
  level:
    org:
    springframework: debug
    objectweb: debug
    root: debug
    com.mapapi.food: debug

server:
  port: 8088


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.84:3306/a_eat_db?useSSL=false&allowMultiQueries=true
    username: a_eat_user
    password: "!adnstyleDB"
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern:  /static/**

mybatis:
  mapper-locations: mybatis/**/*Mapper.xml